import Head from "next/head";
import React, { useState } from "react";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";

export default function Feed() {
  const [title] = useState("Demo DAO");
  const [timeElapsed] = useState("14m");
  const [post, setPost] = useState("");
  const [posts, setPosts] = useState([
    "Wow!",
    "Demo DAO hit another milestone! The first 100 members joined it!",
  ]);

  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <div className="container flex bg-[#1B202A] min-h-screen">
          <div className="pt-[20px] grow">
            <div className="bg-[#2A2F3B] rounded-lg py-3 pr-6 mt-4 flex items-center">
              <div className="mx-5 text-[#5B6372]">Logo</div>
              <textarea
                className="bg-[#333A46] text-white placeholder:text-[#5B6372] rounded-md py-2 px-5 w-full outline-none"
                placeholder="Write a post"
                value={post}
                onChange={(e) => setPost(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    setPosts([post, ...posts]);
                    setPost("");
                  }
                }}
              ></textarea>
            </div>
            {posts.map((content, index) => {
              return (
                <div
                  className="bg-[#2A2F3B] rounded-lg p-5 mt-4 text-gray-200"
                  key={index}
                >
                  <div className="flex justify-between mb-5">
                    <div>{title}</div>
                    <div className="text-gray-500">{timeElapsed}</div>
                  </div>
                  <p className="my-1" key={index}>
                    {content}
                  </p>
                  )
                </div>
              );
            })}
          </div>
        </div>
      </MainContainer>
    </>
  );
}
