import Head from "next/head";
import React, { useState } from "react";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";
import feeds from "../../mocks/feeds";

export default function Feed() {
  const [newPost, setNewPost] = useState("");
  const [posts, setPosts] = useState(feeds);

  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <div className="container flex bg-[#1B202A] min-h-screen">
          <div className="pt-[20px] grow">
            <div className="bg-secondary rounded-lg py-3 pr-6 mt-4 flex items-center">
              <textarea
                className="bg-[#333A46] text-white placeholder:text-[#5B6372] rounded-md ml-5 py-2 px-5 w-full outline-none"
                placeholder="Write a post"
                value={newPost}
                onChange={(e) => setNewPost(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    setPosts([
                      { title: "", timeElapsed: "14m", text: [newPost] },
                      ...posts,
                    ]);
                    setNewPost("");
                  }
                }}
              ></textarea>
            </div>
            {posts.map((post, index) => {
              return (
                <div
                  className="bg-secondary rounded-lg p-5 mt-4 text-gray-200"
                  key={index}
                >
                  <div className="flex justify-between mb-5">
                    <div>{post.title}</div>
                    <div className="text-gray-500">{post.timeElapsed}</div>
                  </div>
                  {post.text.map((paragraph, index) => {
                    return (
                      <p className="my-1" key={index}>
                        {paragraph}
                      </p>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
      </MainContainer>
    </>
  );
}
