import Head from "next/head";
import React, { useState } from "react";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";
import TextareaAutosize from "react-textarea-autosize";
import feeds from "../../mocks/feeds";

export default function Feed() {
  const [newPost, setNewPost] = useState("");
  const [isWriting, setIsWriting] = useState(false);
  const [posts, setPosts] = useState(feeds);

  return (
    <>
      <Head>
        <title>Feed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <div className="container flex bg-transparent min-h-screen">
          <div className="pt-[20px] grow">
            <div className="bg-secondary rounded-lg p-5 mt-4 flex flex-col items-start">
              <div
                className="bg-neutral text-white rounded-md py-2 px-5 w-full outline-none"
                onClick={() =>
                  isWriting ? setIsWriting(false) : setIsWriting(true)
                }
                onFocus={() => setIsWriting(true)}
                onBlur={() => setIsWriting(false)}
              >
                {!isWriting && !newPost ? (
                  <span className="text-[#5B6372]">Write your post</span>
                ) : (
                  <TextareaAutosize
                    className="bg-transparent py-2 outline-none w-full resize-none text-base"
                    value={newPost}
                    onChange={(e) => setNewPost(e.target.value)}
                    autoFocus
                  />
                )}
              </div>
              <button
                className="bg-accent rounded-md mt-3 px-5 py-2 text-white font-bold"
                onClick={() => {
                  if (newPost) {
                    setPosts((prev) => [
                      {
                        title: "DEMO DAO",
                        timeElapsed: "14m",
                        text: newPost.split("\n"),
                      },
                      ...prev,
                    ]);
                    setNewPost("");
                  }
                }}
              >
                Post
              </button>
            </div>
            {posts.map((post, index) => {
              return (
                <div
                  className="bg-secondary rounded-lg p-5 mt-4 text-gray-200"
                  key={index}
                >
                  <div className="flex justify-between mb-5">
                    <div>{post.title}</div>
                    <div className="text-gray-500">{post.timeElapsed}</div>
                  </div>
                  {post.text.map((paragraph, index) => {
                    return (
                      <p className="my-1 break-all" key={index}>
                        {paragraph}
                      </p>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
      </MainContainer>
    </>
  );
}
