import Head from "next/head";
import React, { useState } from "react";
import Header from "../../components/Header";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";
import TableContent from "../../containers/TableContent";
import dao from "../../mocks/dao";

export default function About() {
  const [title] = useState(dao.title);
  const [description] = useState(dao.description);
  const [nftsList] = useState(dao.nftsList);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <Header description={description} name={title} address={""} />
        <TableContent nftsList={nftsList} />
      </MainContainer>
    </>
  );
}
