import React, { useState } from "react";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";
import Head from "next/head";
import SearchBar from "../../components/SearchBar";
import FilteringTags from "../../components/FilteringTags";
import MembersList from "../../components/MembersList";
import { IMember } from "../../interfaces/IMember";

export default function Members() {
  const [members] = useState<IMember[]>([
    {
      name: "user.eth",
      role: "Admin",
    },
    {
      name: "user2.eth",
      role: "Member",
    },
    {
      name: "user3.eth",
      role: "Whitelist",
    },
    {
      name: "user4.eth",
      role: "Unsigned",
    },
    {
      name: "user5.eth",
      role: "Unsigned",
    },
    {
      name: "user6.eth",
      role: "Unsigned",
    },
  ]);
  const [tagsByRole] = useState([
    "All",
    "Admin",
    "Member",
    "Unsigned",
    "Whitelist",
  ]);
  const [activeTag, setActiveTage] = useState(0);
  const [query, setQuery] = useState("");

  return (
    <>
      <Head>
        <title>Members</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <SearchBar query={query} setQuery={setQuery} />
        <main className="mt-[20px] bg-[#242A35] pt-[30px] px-[30px] rounded-[15px]">
          <FilteringTags
            members={members}
            tagsByRole={tagsByRole}
            activeTag={activeTag}
            setActiveTage={setActiveTage}
          />
          <MembersList
            members={members}
            tagsByRole={tagsByRole}
            activeTag={activeTag}
            query={query}
          />
        </main>
      </MainContainer>
    </>
  );
}
