import React, { useState } from "react";
import Navigation from "../../components/Navigation";
import MainContainer from "../../containers/MainContainer";
import Head from "next/head";
import SearchBar from "../../components/SearchBar";
import FilteringTags from "../../components/FilteringTags";
import MembersList from "../../components/MembersList";
import { IMember } from "../../interfaces/IMember";
import membersList from "../../mocks/membersList";

export default function Members() {
  const [members] = useState<IMember[]>(membersList.list);
  const [tagsByRole] = useState(membersList.tagsByRole);
  const [activeTag, setActiveTage] = useState(0);
  const [query, setQuery] = useState("");

  return (
    <>
      <Head>
        <title>Members</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <SearchBar query={query} setQuery={setQuery} />
        <main className="mt-[20px] bg-secondary pt-[30px] px-[30px] rounded-[15px]">
          <FilteringTags
            members={members}
            tagsByRole={tagsByRole}
            activeTag={activeTag}
            setActiveTage={setActiveTage}
          />
          <MembersList
            members={members}
            tagsByRole={tagsByRole}
            activeTag={activeTag}
            query={query}
          />
        </main>
      </MainContainer>
    </>
  );
}
