import Head from "next/head";
import React, { useState } from "react";
import MainContainer from "../../containers/MainContainer";

export default function Settings() {
  const [displayName, setDisplayName] = useState("");
  const [publicUrl, setPublicUrl] = useState(
    "app.daoproject.com/users/453c43jsdcc"
  );
  const [bio, setBio] = useState("");
  const [email, setEmail] = useState("");
  const [walletAddress, setWalletAddress] = useState(
    "0x3B31f54678Da6aC1BFE6A93aa0D4a776f726115c"
  );
  const [links, setLinks] = useState({
    personalSite: "",
    twitter: "",
    instagram: "",
    telegram: "",
    discord: "",
  });
  return (
    <>
      <Head>
        <title>Profile Edit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className="flex justify-center">
          <div className="w-[560px] text-white">
            <div className="text-2xl font-bold">Edit profile</div>
            <div className="mt-5 flex gap-3 font-semibold">
              <div className="w-32">
                Profile image
                <div className="mt-2 rounded-full w-20 h-20 bg-[rgb(255,26,91)]"></div>
              </div>
              <div className="w-full">
                Cover image
                <div className="mt-2 rounded-md h-20 bg-[rgb(26,224,255)]"></div>
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Display name</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  placeholder="Enter your display name"
                  value={displayName}
                  onChange={(e) => setDisplayName(e.target.value)}
                />
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Public URL</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  value={publicUrl}
                  onChange={(e) => setPublicUrl(e.target.value)}
                />
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Bio</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  placeholder="Enter your bio"
                  value={bio}
                  onChange={(e) => setBio(e.target.value)}
                />
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Email (for notifications only)</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  placeholder="Enter your email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Wallet address</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  value={walletAddress}
                  onChange={(e) => setWalletAddress(e.target.value)}
                />
              </div>
            </div>
            <div className="mt-5">
              <label htmlFor="">Links</label>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                <input
                  type="text"
                  className="border-none bg-transparent outline-none w-full"
                  placeholder="Personal site link"
                  value={links.personalSite}
                  onChange={(e) =>
                    setLinks((prev) => ({
                      ...prev,
                      personalSite: e.target.value,
                    }))
                  }
                />
              </div>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md flex">
                <span>twitter.com/</span>
                <input
                  type="text"
                  className="border-none bg-transparent outline-none ml-1 w-full"
                  placeholder="Twitter link or username"
                  value={links.twitter}
                  onChange={(e) =>
                    setLinks((prev) => ({
                      ...prev,
                      twitter: e.target.value,
                    }))
                  }
                />
              </div>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md flex">
                <span>instagram.com/</span>
                <input
                  type="text"
                  className="border-none bg-transparent outline-none ml-1 w-full"
                  placeholder="Instagram link or username"
                  value={links.instagram}
                  onChange={(e) =>
                    setLinks((prev) => ({
                      ...prev,
                      instagram: e.target.value,
                    }))
                  }
                />
              </div>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md flex">
                <span>t.me/</span>
                <input
                  type="text"
                  className="border-none bg-transparent outline-none ml-1 w-full"
                  placeholder="Telegram link or username"
                  value={links.telegram}
                  onChange={(e) =>
                    setLinks((prev) => ({
                      ...prev,
                      telegram: e.target.value,
                    }))
                  }
                />
              </div>
              <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md flex">
                <span>discord.com/invite/</span>
                <input
                  type="text"
                  className="border-none bg-transparent outline-none ml-1 w-full"
                  placeholder="Discord server link"
                  value={links.discord}
                  onChange={(e) =>
                    setLinks((prev) => ({
                      ...prev,
                      discord: e.target.value,
                    }))
                  }
                />
              </div>
            </div>
            <div className="mt-7 mb-7">
              <input
                type="button"
                value="Save"
                className="h-11 px-[30px] grid place-items-center bg-[#F07300] text-white text-base font-bold rounded-lg cursor-pointer"
              />
            </div>
          </div>
        </div>
      </MainContainer>
    </>
  );
}
