import Head from "next/head";
import React, { useState } from "react";
import Header from "../components/Header";
import Navigation from "../components/Navigation";
import MainContainer from "../containers/MainContainer";

export default function About() {
  const [title] = useState("Demo DAO");
  const [link] = useState("superdao.co/demodao");
  const [description] =
    useState(`Welcome to the demo DAO Enjoy your experience of being part of
  your first DAO`);
  const [tags] = useState(["Smart Contract", "Support", "Creator guide"]);
  const [amountOfNFTs] = useState(3);
  const [amountInCrypto] = useState("5000 MATIC");
  const [amountInUSD] = useState("3 126.52USD");
  const [heldTokens] = useState(8);
  const [overallTokens] = useState(1000);
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Navigation />
        <Header description={description} tags={tags} name={title} address={link} />
        <div className="w-full pt-5">
          <div className="flex justify-between w-full">
            <div className="text-white font-bold">
              Membership NFTs
              <span className="text-slate-600 ml-2">{amountOfNFTs}</span>
            </div>
            <div className="text-[#F07300] font-semibold">Customize</div>
          </div>
          <div className="mt-5 mb-24">
            <div className="bg-[#2A2F3B] w-60 p-3 rounded-lg flex flex-col">
              <div className="h-60 w-52 bg-zinc-500 rounded-md mt-3 self-center"></div>
              <div className="text-[#767F91] mt-3 text-sm">
                {title} . {heldTokens} of {overallTokens}
              </div>
              <div className="text-white font-bold mt-2">Core team</div>
              <div className="text-[#F07300] mt-1 mb-3">
                {amountInCrypto}
                <span className="text-[#767F91] text-sm ml-2">
                  ({amountInUSD})
                </span>
              </div>
            </div>
          </div>
        </div>
      </MainContainer>
    </>
  );
}
