import React, { useState } from "react";
import Head from "next/head";
import MainContainer from "../containers/MainContainer";

export default function CreateVoting() {
  const [votingType, setVotingType] = useState("Send MATIC");
  const [recipientAddress, setRecipientAddress] = useState("0x3423412a5b3m");
  const [value, setValue] = useState("0.1");

  return (
    <>
      <Head>
        <title>Create Voting</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className="text-white">
          <div className="text-2xl font-bold mb-2">
            Create voting in DemoDao
          </div>
          <div className="text-sm mb-8">
            After creating a voting, you can activate it when the quorum is
            reached
          </div>
          <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
            <input
              className="bg-transparent outline-none"
              value={votingType}
              onChange={(e) => setVotingType(e.target.value)}
            />
          </div>

          <div className="mt-5 font-semibold">
            Transfer MATIC from DAO balance
          </div>
          <div className="mt-2">Recipient address</div>
          <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
            <input
              className="bg-transparent outline-none"
              value={recipientAddress}
              onChange={(e) => setRecipientAddress(e.target.value)}
            />
          </div>

          <div className="mt-3">MATIC amount</div>
          <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
            <input
              className="bg-transparent outline-none"
              value={value}
              type="text"
              onChange={(e) => setValue(e.target.value)}
            />
          </div>
          <div className="mt-3">Title</div>
          <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
            <input
              className="bg-transparent outline-none"
              value={`${votingType} to ${recipientAddress}`}
              type="text"
            />
          </div>
          <div className="mt-3">Description</div>
          <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
            <input
              className="bg-transparent outline-none"
              value={`${votingType} to Bob`}
              type="text"
            />
          </div>
          <div className="mt-7 mb-7">
            <input
              type="button"
              value="Create voting"
              className="h-11 px-[30px] grid place-items-center bg-accent text-white text-base font-bold rounded-lg cursor-pointer"
            />
          </div>
        </div>
      </MainContainer>
    </>
  );
}
