import Head from "next/head";
import React, { useState } from "react";
import DaoNameForm from "../components/DaoNameForm";
import PartnersSettingForm from "../components/PartnersSettingForm";
import QuorumSettingForm from "../components/QuorumSettingForm";
import MainContainer from "../containers/MainContainer";

export default function CreateDao() {
  const [newDao, setNewDao] = useState({ name: "", symbol: "" });
  const [partners, setPartners] = useState([{ address: "", tokens: 1 }]);
  const [quorum, setQuorum] = useState(40);
  return (
    <>
      <Head>
        <title>Create a DAO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className="flex justify-center">
          <div className="w-[560px] text-white">
            <div className="text-2xl font-bold">Create a DAO</div>
            <div className="mt-1 text-sm">
              Choose name and symbol for the DAO, Government token will get the
              same parameters. Distribute government tokens between addresses
              that will participate in voting
            </div>
            <DaoNameForm newDao={newDao} setNewDao={setNewDao} />
            <PartnersSettingForm
              partners={partners}
              setPartners={setPartners}
            />
            <QuorumSettingForm quorum={quorum} setQuorum={setQuorum} />
            <div className="mt-7 mb-7">
              <input
                type="button"
                value="Create a DAO"
                className="h-11 px-[30px] grid place-items-center bg-accent text-white text-base font-bold rounded-lg cursor-pointer"
              />
            </div>
          </div>
        </div>
      </MainContainer>
    </>
  );
}
