import Head from "next/head";
import React from "react";
import MainContainer from "../containers/MainContainer";

export default function createDao() {
  return (
    <>
      <Head>
        <title>Create a DAO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <div className="flex justify-center">
          <div className="w-[560px] text-white">
            <div className="text-2xl font-bold">Create a DAO</div>
            <div className="mt-1 text-sm">
              Choose name and symbol for the DAO, Government token will get the
              same parameters. Distribute government tokens between addresses
              that will participate in voting
            </div>
            <div className="mt-10">
              <div className="text-lg">Name your DAO</div>
              <div className="mt-5">
                <label htmlFor="">DAO name</label>
                <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                  <input
                    type="text"
                    className="border-none bg-transparent outline-none"
                    placeholder="Enter your DAO name"
                  />
                </div>
                <div className="mt-3">
                  <label htmlFor="">DAO symbol</label>
                  <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                    <input
                      type="text"
                      className="border-none bg-transparent outline-none"
                      placeholder="Enter your DAO symbol"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-10">
              <div className="text-lg">Set up your partners & Shares</div>
              <div className="mt-5">
                <label htmlFor="">Partner address</label>
                <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                  <input
                    type="text"
                    className="border-none bg-transparent outline-none"
                    placeholder="Enter a partner address"
                  />
                </div>
                <div className="mt-3">
                  <label htmlFor="">Government token amount</label>
                  <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                    <input
                      type="text"
                      className="border-none bg-transparent outline-none"
                      placeholder="1"
                    />
                  </div>
                </div>
                <div className="mt-7 mb-7">
                  <input
                    type="button"
                    value="Add a partner"
                    className="h-11 px-[30px] grid place-items-center bg-[#F07300] text-white text-base font-bold rounded-lg cursor-pointer"
                  />
                </div>
              </div>
            </div>
            <div className="mt-10">
              <div className="text-lg">Set up a Quorum</div>
              <div className="mt-5">
                <label htmlFor="">Quorum</label>
                <div className="mt-3 bg-[rgba(208,220,245,0.08)] py-2 px-3 rounded-md">
                  <input
                    type="number"
                    className="border-none bg-transparent outline-none"
                    // value="2"
                  />
                  <input
                    type="range"
                    className="border-none bg-transparent outline-none"
                    placeholder="Enter a partner address"
                  />
                </div>
              </div>
            </div>
            <div className="mt-7 mb-7">
              <input
                type="button"
                value="Create a DAO"
                className="h-11 px-[30px] grid place-items-center bg-[#F07300] text-white text-base font-bold rounded-lg cursor-pointer"
              />
            </div>
          </div>
        </div>
      </MainContainer>
    </>
  );
}
