import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>DAO Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex bg-[#1B202A] h-screen">
        <aside className="bg-[#343A46] w-[79px] h-screen flex flex-col justify-between">
          <div>
            <div className="h-[90px] grid place-items-center border-l-2 border-[#F07300]">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="w-[30px] h-[30px] fill-[#F07300] cursor-pointer"
              >
                <path
                  fillRule="evenodd"
                  d="M3 6a3 3 0 013-3h2.25a3 3 0 013 3v2.25a3 3 0 01-3 3H6a3 3 0 01-3-3V6zm9.75 0a3 3 0 013-3H18a3 3 0 013 3v2.25a3 3 0 01-3 3h-2.25a3 3 0 01-3-3V6zM3 15.75a3 3 0 013-3h2.25a3 3 0 013 3V18a3 3 0 01-3 3H6a3 3 0 01-3-3v-2.25zm9.75 0a3 3 0 013-3H18a3 3 0 013 3V18a3 3 0 01-3 3h-2.25a3 3 0 01-3-3v-2.25z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="h-[90px] grid place-items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-[30px] h-[30px] stroke-[#B3B9C5] cursor-pointer"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z"
                />
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 18a3.75 3.75 0 00.495-7.467 5.99 5.99 0 00-1.925 3.546 5.974 5.974 0 01-2.133-1A3.75 3.75 0 0012 18z"
                />
              </svg>
            </div>
            <div className="h-[90px] grid place-items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-[30px] h-[30px] stroke-[#B3B9C5] cursor-pointer"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
                />
              </svg>
            </div>
          </div>
          <div className="mb-[30px]">
            <div className="h-[90px] grid place-items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-[30px] h-[30px] stroke-[#B3B9C5] cursor-pointer mb-[30px]"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z"
                />
              </svg>
              <Image
                src={"/"}
                alt={" "}
                className="bg-gray-500 border-gray-800 rounded-full"
                height="30px"
                width="30px"
              />
            </div>
          </div>
        </aside>
        <aside className="bg-[#252B36] w-[351px] h-screen">
          <div className="flex justify-between mb-[30px] mt-[21px] mx-[21px]">
            <div className="text-[#FAFAFB] text-[33px] font-bold">DAOs</div>
            <button className="grid place-items-center">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-[23px] h-[23px] stroke-[#B3B9C5]"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 4.5v15m7.5-7.5h-15"
                />
              </svg>
            </button>
          </div>

          <ul className="mx-[10px]">
            <li className="flex flex-row px-[14px] py-[8px]">
              <div className="mr-[20px]">
                <Image
                  src={"/"}
                  alt={" "}
                  className="bg-gray-500 border-gray-800 rounded-full"
                  height="50px"
                  width="50px"
                />
              </div>
              <div className="text-[18px]">
                <div className="text-white font-medium">Charm Verse</div>
                <div className="text-[#B3B9C5] font-light">2.3k members</div>
              </div>
            </li>
            <li className="flex flex-row px-[14px] py-[8px] after:content-[''] inset-0 bg-[#333945] rounded-[9px]">
              <div className="mr-[20px]">
                <Image
                  src={"/"}
                  alt={" "}
                  className="bg-gray-500 border-gray-800 rounded-full"
                  height="50px"
                  width="50px"
                />
              </div>
              <div className="text-[18px]">
                <div className="text-white font-medium">Charm Verse</div>
                <div className="text-[#B3B9C5] font-light">2.3k members</div>
              </div>
            </li>
          </ul>
        </aside>
        <div className="pt-[20px] px-[52px] grow">
          <nav className="flex justify-between h-[40px] items-center mb-[30px]">
            <div className="text-[33px] text-[#FAFAFB] font-bold">DEMO DAO</div>
            <ul className="flex gap-[30px] h-min text-white font-bold text-[19px]">
              <li className="text-white font-bold text-[19px] cursor-pointer">
                About
              </li>
              <li className="text-white font-bold text-[19px] cursor-pointer">
                Members
              </li>
              <li className="text-white font-bold text-[19px] cursor-pointer">
                Treasure
              </li>
              <li className="text-white font-bold text-[19px] cursor-pointer">
                Feed
              </li>
              <li className="text-white font-bold text-[19px] cursor-pointer">
                Voting
              </li>
              <li className="flex items-center cursor-pointer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM12.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0zM18.75 12a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"
                  />
                </svg>
              </li>
            </ul>
          </nav>
          <div className="flex justify-between">
            <input
              type="search"
              name=""
              id=""
              placeholder="Name or wallet address "
              className="bg-[#252B36] w-[340px] h-[50px] px-[14px] pl-[43px] rounded-[8px] font-[19px] text-white outline-none"
            />
            <div className="flex">
              <div className="h-[50px] w-[50px] bg-[#2A2F3B] rounded-[11px] grid place-items-center mr-[20px] cursor-pointer">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={2}
                  stroke="currentColor"
                  className="w-[25px] h-[25px] stroke-[#B3B9C5]"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5"
                  />
                </svg>
              </div>
              <input
                type="button"
                value="Add members"
                className="h-[50px] px-[30px] grid place-items-center bg-[#F07300] text-white text-[19px] font-bold rounded-[10px] cursor-pointer"
              />
            </div>
          </div>
          <main className="mt-[20px] bg-[#242A35] pt-[30px] px-[30px] rounded-[15px]">
            <ul className="flex gap-[15px]">
              <li className="px-[20px] py-[10px] bg-[#F07300] rounded-[25px] text-white text-[17px] font-medium">
                All <span className="font-normal">124</span>
              </li>
              <li className="px-[20px] py-[10px] bg-[#39404C] rounded-[25px] text-[#F5F5F5] text-[17px] font-medium">
                Admin <span className="font-normal text-[#A0A6B2]">5</span>
              </li>
              <li className="px-[20px] py-[10px] bg-[#39404C] rounded-[25px] text-[#F5F5F5] text-[17px] font-medium">
                Member <span className="font-normal text-[#A0A6B2]">95</span>
              </li>
              <li className="px-[20px] py-[10px] bg-[#39404C] rounded-[25px] text-[#F5F5F5] text-[17px] font-medium">
                Unsigned <span className="font-normal text-[#A0A6B2]">24</span>
              </li>
              <li className="px-[20px] py-[10px] bg-[#39404C] rounded-[25px] text-[#F5F5F5] text-[17px] font-medium">
                Whitelist <span className="font-normal text-[#A0A6B2]">52</span>
              </li>
            </ul>
            <table className="mt-[25px] text-left text-[#B3B9C5]">
              <thead className="h-[50px]">
                <tr>
                  <th className="w-[200px]" colSpan={2}>
                    Member
                  </th>
                  <th className="w-[250px]">Role</th>
                  <th>Tier</th>
                </tr>
              </thead>
              <tbody>
                <tr className="h-[60px]">
                  <td className="h-[60px] w-[30px] flex items-center justify-start">
                    <Image
                      src="/"
                      alt=" "
                      height="28px"
                      width="28px"
                      className="bg-[#D9D9D9] rounded-full"
                    />
                  </td>
                  <td className="text-white">rndmking.eth</td>
                  <td>Admin</td>
                  <td>Core Team</td>
                </tr>
              </tbody>
            </table>
          </main>
        </div>
      </div>
    </>
  );
};

export default Home;
