import React, { useState } from "react";
import Head from "next/head";
import MainContainer from "../containers/MainContainer";
import Header from "../components/Header";
import TableContent from "../containers/TableContent";
import profile from "../mocks/profile";

export default function Profile() {
  const [daosList] = useState(profile.daosList);
  const [nftsList] = useState(profile.nftsList);
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header/>
        <TableContent daosList={daosList} nftsList={nftsList} />
      </MainContainer>
    </>
  );
}
