import React, { useState } from "react";
import { useAddress } from "@thirdweb-dev/react";
import Head from "next/head";
import MainContainer from "../containers/MainContainer";
import Header from "../components/Header";
import TableContent from "../containers/TableContent";

export default function Profile() {
  const address = useAddress();
  const [daosList] = useState([
    {
      name: "Verification DAO",
      role: "admin",
      description: "This DAO grants you special NFT as a Proof of Verification",
      members: 2,
    },
  ]);
  const [nftsList] = useState([
    { role: "Creator", collectionName: "DAO Heroes", daoName: "My first DAO" },
  ]);
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header address={address} />
        <TableContent daosList={daosList} nftsList={nftsList} />
      </MainContainer>
    </>
  );
}
