import React from "react";
import Head from "next/head";
import MainContainer from "../containers/MainContainer";
import Header from "../components/Header";
import TableContent from "../containers/TableContent";

export default function profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header />
        <TableContent />
      </MainContainer>
    </>
  );
}
